databases:
  - name: alx-backend-security
    plan: free
    databaseName: alxbackendsecurity
    user: alx

services:
  - type: web
    plan: free
    name: alx-backend-security
    runtime: python
    buildCommand: './build.sh'
    startCommand: 'python -m gunicorn alx-backend-security.asgi:application -k uvicorn.workers.UvicornWorker'
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: alx-backend-securitydb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4